CXX=g++
CXXFLAGS=-std=c++17 -g -O0

all: BestSubsequence

BestSubsequence: BestSubsequence.cpp MostPositiveSubsequence.cpp MostPositiveSubsequence.h
	$(CXX) $(CXXFLAGS) BestSubsequence.cpp MostPositiveSubsequence.cpp -o BestSubsequence

clean:
	rm -f BestSubsequence
